---
# tasks file for ansible-role-freebsd_pkg

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ freebsd_pkg_log_dir }}"
    mode: 0755
    owner: "{{ freebsd_pkg_user }}"
    group: "{{ freebsd_pkg_group }}"
    state: directory
  notify: Restart freebsd_pkg

- name: Create db directory
  file:
    path: "{{ freebsd_pkg_db_dir }}"
    mode: 0755
    owner: "{{ freebsd_pkg_user }}"
    group: "{{ freebsd_pkg_group }}"
    state: directory
  notify: Restart freebsd_pkg

- name: Create freebsd_pkg.conf
  template:
    src: freebsd_pkg.conf.j2
    dest: "{{ freebsd_pkg_conf_file }}"
    validate: echo %s
  notify: Restart freebsd_pkg

- name: Start freebsd_pkg
  service:
    name: "{{ freebsd_pkg_service }}"
    enabled: true
    state: started
